# Generated by Django 4.0.3 on 2022-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OkangaShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okanga',
            name='initial_item_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
